language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
  
before_install:
  - docker build -t myfirsttravisspringBoot -f DockerFile.dev .
   
script:
  - docker run myFirstTravisSpringBoot 