language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
 
before_install:
  - docker build -t myfirsttravisspringboot -f DockerFile.dev .
  
script:
  - ./mvnw clean install -B
  - docker run myfirsttravisspringboot -- --coverage